version: '3.8'

services:
  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - productservice
      - catalogservice
      - cartservice
    networks:
      - microservices-network

  productservice:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - microservices-network

  catalogservice:
    build:
      context: ./CatalogService
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - microservices-network

  cartservice:
    build:
      context: ./CartService
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge


